from __future__ import annotations

import json
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from urllib.parse import urlparse

ROOT = Path(__file__).resolve().parent
STATIC_ROOT = ROOT
DEFAULT_PORT = 8000


class TestHostHandler(BaseHTTPRequestHandler):
    server_version = "TeacherSupportTestHost/1.0"

    def log_message(self, format: str, *args) -> None:
        print(f"{self.address_string()} - {format % args}")

    def _send_json(self, status: int, payload: dict) -> None:
        body = json.dumps(payload, ensure_ascii=False).encode("utf-8")
        self.send_response(status)
        self.send_header("Content-Type", "application/json; charset=utf-8")
        self.send_header("Content-Length", str(len(body)))
        self.send_header("Access-Control-Allow-Origin", "*")
        self.end_headers()
        self.wfile.write(body)

    def _send_text(self, status: int, text: str, content_type: str = "text/plain; charset=utf-8") -> None:
        body = text.encode("utf-8")
        self.send_response(status)
        self.send_header("Content-Type", content_type)
        self.send_header("Content-Length", str(len(body)))
        self.send_header("Access-Control-Allow-Origin", "*")
        self.end_headers()
        self.wfile.write(body)

    def _serve_file(self, path: Path) -> None:
        if not path.exists() or not path.is_file():
            self.send_error(404, "Not Found")
            return
        content_type = "text/plain; charset=utf-8"
        if path.suffix == ".html":
            content_type = "text/html; charset=utf-8"
        elif path.suffix == ".css":
            content_type = "text/css; charset=utf-8"
        elif path.suffix == ".js":
            content_type = "application/javascript; charset=utf-8"
        elif path.suffix == ".md":
            content_type = "text/markdown; charset=utf-8"
        elif path.suffix == ".json":
            content_type = "application/json; charset=utf-8"
        body = path.read_bytes()
        self.send_response(200)
        self.send_header("Content-Type", content_type)
        self.send_header("Content-Length", str(len(body)))
        self.send_header("Access-Control-Allow-Origin", "*")
        self.end_headers()
        self.wfile.write(body)

    def do_OPTIONS(self) -> None:
        self.send_response(204)
        self.send_header("Access-Control-Allow-Origin", "*")
        self.send_header("Access-Control-Allow-Methods", "GET, POST, OPTIONS")
        self.send_header("Access-Control-Allow-Headers", "Content-Type, Authorization")
        self.end_headers()

    def do_GET(self) -> None:
        parsed = urlparse(self.path)
        if parsed.path == "/health":
            return self._send_json(200, {"ok": True, "service": "TeacherSupport test host"})
        if parsed.path == "/":
            return self._serve_file(STATIC_ROOT / "index.html")
        if parsed.path.startswith("/v1/"):
            return self.send_error(405, "Method Not Allowed")

        target = (STATIC_ROOT / parsed.path.lstrip("/")).resolve()
        if not str(target).startswith(str(STATIC_ROOT.resolve())):
            return self.send_error(403, "Forbidden")
        if target.is_dir():
            target = target / "index.html"
        return self._serve_file(target)

    def do_POST(self) -> None:
        parsed = urlparse(self.path)
        if parsed.path == "/v1/chat/completions":
            return self.handle_chat_completions()
        return self.send_error(404, "Not Found")

    def handle_chat_completions(self) -> None:
        length = int(self.headers.get("Content-Length", "0") or "0")
        raw_body = self.rfile.read(length).decode("utf-8") if length else "{}"
        try:
            payload = json.loads(raw_body)
        except json.JSONDecodeError:
            payload = {}

        user_text = ""
        messages = payload.get("messages") or []
        for message in reversed(messages):
            if message.get("role") == "user":
                user_text = message.get("content", "")
                break

        language = "EN"
        model_name = payload.get("model", "qwen2.5-3b-instruct")
        if "\"language\": \"SK\"" in user_text or '"language": "SK"' in user_text:
            language = "SK"

        title = "TeacherSupport lesson plan" if language == "EN" else "Plán hodiny TeacherSupport"
        summary = (
            "Practical lesson plan generated by the local test host."
            if language == "EN"
            else "Praktický plán hodiny vygenerovaný lokálnym testovacím hostom."
        )

        blocks = [
            {"title": "Warm-up" if language == "EN" else "Rozohriatie", "minutes": 10, "description": "Short starter activity." if language == "EN" else "Krátka úvodná aktivita."},
            {"title": "Guided practice" if language == "EN" else "Riadené precvičenie", "minutes": 15, "description": "Teacher-led examples with feedback." if language == "EN" else "Ukážky vedené učiteľom so spätnou väzbou."},
            {"title": "Independent task" if language == "EN" else "Samostatná úloha", "minutes": 10, "description": "Short independent work." if language == "EN" else "Krátka samostatná práca."},
            {"title": "Exit ticket" if language == "EN" else "Exit ticket", "minutes": 10, "description": "Quick check and homework suggestion." if language == "EN" else "Rýchla kontrola a návrh domácej úlohy."},
        ]

        response = {
            "id": "chatcmpl-local-test",
            "object": "chat.completion",
            "created": 0,
            "model": model_name,
            "choices": [
                {
                    "index": 0,
                    "finish_reason": "stop",
                    "message": {
                        "role": "assistant",
                        "content": json.dumps(
                            {
                                "title": title,
                                "summary": summary,
                                "blocks": blocks,
                                "checklistInterpretation": {
                                    "pre": "Student seems ready." if language == "EN" else "Žiak vyzerá pripravený.",
                                    "post": "Goal was mostly achieved." if language == "EN" else "Cieľ bol väčšinou splnený.",
                                },
                                "adaptation": {
                                    "summary": "Use the next lesson to increase challenge slightly." if language == "EN" else "V ďalšej hodine mierne zvýš náročnosť.",
                                    "bullets": [
                                        "Keep blocks short.",
                                        "Use one more check question."
                                    ] if language == "EN" else [
                                        "Udrž bloky krátke.",
                                        "Pridaj ešte jednu kontrolnú otázku."
                                    ]
                                },
                                "riskFlags": [],
                                "teacherNote": "Local test host response."
                            },
                            ensure_ascii=False
                        )
                    }
                }
            ]
        }
        self._send_json(200, response)


def main() -> None:
    port = DEFAULT_PORT
    server = ThreadingHTTPServer(("127.0.0.1", port), TestHostHandler)
    print(f"TeacherSupport local test host running at http://127.0.0.1:{port}")
    print("Static app: http://127.0.0.1:{port}/")
    print("Mock model endpoint: /v1/chat/completions")
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        print("Shutting down...")
    finally:
        server.server_close()


if __name__ == "__main__":
    main()
